spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      enabled: true

logging.level:
  org.hibernate.SQL: debug

