version: '3.8'

services:

  mysql:
    image: mysql:8.1
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PW}"
    ports:
      - "3306:3306"
