spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sys"
    username: "root"
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:29092

logging.level:
  org.hibernate.SQL: debug


