version: '3.8'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  test-dashboard:
    image: grafana/grafana:8.5.21
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana
    ports:
      - "3001:3000"     # To avoid with application grafana

    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./k6/dashboards/k6-load-testing-result.json:/var/lib/grafana/dashboards/k6-load-testing-result.json
      - ./k6/dashboards/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./k6/dashboards/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6/scripts:/scripts