name: Java CI with Gradle

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: MySQL container up by docker-compose
        run: docker-compose -f ./monitoring/docker-compose.yml up --wait

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test and Build with Gradle Wrapper
        run: ./gradlew test

